### PR TITLE
add checking for hardlinks

### PR DESCRIPTION
**Pull request by mingwandroid**
For your consideration @ilanschnell

### CODE REVIEW

**Comment by ilanschnell** [comment]
I would do it more like this:

```
for m in self.t.getmembers():
    if m.islnk():
        raise PackageError('hardlink found: %s' % m.path)
```

Besides the implementation details, I'm not sure when this can happen.

**Comment by mingwandroid** [comment]
Well, the `ncurses` builds from yesterday had this issue I'm afraid :-(

https://github.com/conda/conda/issues/3030

I put new ones in test-pkgs (build 8), if you can upload them I'd appreciate it.

**Comment by mingwandroid** [comment]
Done.

**Comment by ilanschnell** [comment]
Thanks for the input.  I added the check in cdf9734f5698e853309cd9c54f3629b2e53b3a3f

**Pull request closed without merging**
